base_model: 'stabilityai/stable-diffusion-2-1-base'
dataset_root: '/export/data/vislearn/rother_subgroup/sheid/LAION_LADD/'
ckpt_folder: '/export/data/sheid/LADD_results/checkpoints/training_7'
project_dir: '/export/home/sheid/LADD_AMD/logging'
#resume_from_checkpoint: '/export/data/sheid/LADD_results/checkpoints/training_4/add_v21_base_training4/checkpoint-4250'

data_pkl_name: 'summary.pkl' 
exp_name: 'training7'
project_name: 'add_v21_base'
optimizer: "adamw" # ["adam", "adamw", "adafactor"]


mixed_precision: 'bf16'
report_to: 'wandb'
lr_scheduler: 'constant' # ['linear', 'cosine', 'cosine_with_restarts', 'polynomial', 'constant', 'constant_with_warmup']
D_ts: "0-750" # Timestep choices for Discriminator. Support two formats:
                #choice1: 10, 249, 499, 749 for discrete values.
                #choice2: 0-11, 200-250, 400-500, 700-750 for ranges.
                #default is range 0-750

checkpointing_steps: 250
dataloader_num_workers: 0
gradient_accumulation_steps: 1
max_train_steps: 50000
seed: 1
train_batch_size: 128
validation_steps: 500
lr_warmup_steps: 500
max_checkpoints_to_keep: 3


local_rank: -1
max_grad_norm: 1

enable_xformers_memory_efficient_attention: False
gradient_checkpointing: True
zero_snr: True
multiscale_D: True
misaligned_pairs_D: True
use_fsdp: False
resume_from_checkpoint: False


reconstruction_loss:
  flag: True
  type: "elatentlpips"
  recon_lambda: 1
  elatentlpips:
    encoder: "sd21"
    augment: "bg"
 

generator:
  warm_up: False
  warm_up_steps: 500
  warm_up_prob: [0, 0, 0.5, 0.5]
  noise_prob: [0.7, 0.1, 0.1, 0.1]
  lr: 0.000001
  num_ts: 4  #Number of time steps to sample from the original 1000 time steps for training G. We train one-step model by default"

discriminator:
  noise_conditioning: False
  clip_conditioning: False
  clip_embedding_dim: 320
  noise_embedding_dim: 320
  lr: 0.000001
